---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cars":
    get:
      summary: list cars
      responses:
        '200':
          description: successful
    post:
      summary: create cars
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: integer
                brand:
                  type: string
                model:
                  type: string
                image:
                  type: string
                description:
                  type: string
              required:
              - price
              - brand
              - model
              - image
              - description
  "/api/v1/cars/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show car
      responses:
        '200':
          description: successful
    patch:
      summary: update car
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: integer
                brand:
                  type: string
                model:
                  type: string
                description:
                  type: string
                image:
                  type: string
    put:
      summary: update car
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: integer
                brand:
                  type: string
                model:
                  type: string
                description:
                  type: string
                image:
                  type: string
              required:
              - price
              - brand
              - model
              - image
              - description
    delete:
      summary: delete car
      responses:
        '200':
          description: successful
  "/api/v1/reservations":
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                car_id:
                  type: integer
                reservation_date:
                  type: string
                  format: datetime
                city:
                  type: string
                to_date:
                  type: string
                  format: datetime
              required:
              - username
              - car_id
              - reservation_date
              - city
              - to_date
  "/api/v1/reservations/?username={username}":
    parameters:
    - name: username
      in: path
      description: username
      required: true
      schema:
        type: string
    get:
      summary: user reservations
      responses:
        '200':
          description: successful
  "/api/v1/reservations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      responses:
        '200':
          description: successful
    patch:
      summary: update reservation
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                car_id:
                  type: integer
                reservation_date:
                  type: string
                  format: datetime
                city:
                  type: string
                to_date:
                  type: string
                  format: datetime
    put:
      summary: update reservation
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                car_id:
                  type: integer
                reservation_date:
                  type: string
                  format: datetime
                city:
                  type: string
                to_date:
                  type: string
                  format: datetime
              required:
              - username
              - car_id
              - reservation_date
              - city
              - to_date
    delete:
      summary: delete reservation
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
